pipeline {
    agent {
        label 'main'
    }
    stages {
        stage("ls") {
            steps {
                script {
                    sh "ls"
                }
            }
        }
        stage("mvn clean") {
            steps {
                script {
                    sh "mvn clean package"
                }
            }
        }
    }
}